# Data Configuration
# Input sources, schema, formats

data:
  # S3 Configuration
  s3_bucket: "siva-test-9"
  s3_prefix_2024: "reddit/new_data/2024_data/"
  s3_prefix_2025: "reddit/new_data/2025_data/"
  s3_results_prefix: "reddit/new_data/results/"
  
  # Sampling Configuration
  sample_rate: 0.01  # 1% sampling
  min_samples_per_file: 100
  oversample_rare_events: true
  rare_event_threshold: 0.05  # 5% threshold for rare events
  
  # Text Processing
  max_text_length: 512  # BERT token limit
  min_text_length: 10
  remove_stopwords: true
  handle_emojis: true
  
  # Data Validation
  required_columns:
    - "text"
    - "subreddit"
    - "created_utc"
  
  # File Formats
  input_formats: ["parquet"]
  output_formats: ["parquet", "json", "csv"]
  
  # Data Paths
  raw_data_dir: "data/raw"
  interim_data_dir: "data/interim"
  processed_data_dir: "data/processed"
  external_data_dir: "data/external"
