# Model Configuration
# Hyperparameters, model paths

model:
  # BERT Configuration
  name: "bert-base-uncased"  # Can be changed to distilbert, roberta, etc.
  max_length: 512
  batch_size: 16
  learning_rate: 2e-5
  num_epochs: 3
  warmup_steps: 500
  weight_decay: 0.01
  gradient_accumulation_steps: 1
  dropout_rate: 0.1
  
  # Classification Labels
  labels:
    - "fear"
    - "question"
    - "fear_driven_question"
    - "other"
  
  # Model Paths
  model_dir: "models/checkpoints"
  tokenizer_dir: "models/tokenizer"
  predictions_dir: "results/metrics/predictions"
  
  # Training Configuration
  early_stopping_patience: 3
  validation_split: 0.2
  test_split: 0.2
  
  # Inference Configuration
  prediction_threshold: 0.5
  batch_size_inference: 32
  
  # Model Registry
  model_registry_file: "models/model_registry.json"
  metadata_file: "models/metadata.json"
